## Matrix Aggregations

Finding the

    min
    max
    sum
    etc. 
of tensors

In [1]:
%%time
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(t.__version__)

2.10.0+cpu
CPU times: total: 1.8 s
Wall time: 1.83 s


In [2]:
t1 = t.arange(1,10,2)
t2 = t.arange(0,10,2)
t1,t2

(tensor([1, 3, 5, 7, 9]), tensor([0, 2, 4, 6, 8]))

In [3]:
#min
t.min(t1),t.min(t2)

(tensor(1), tensor(0))

In [17]:
#max
# takes float and complex datatypes
t.max(t1),t.max(t2)
# t.amax(t1),t.max(t2) #IDK

(tensor(9), tensor(8))

In [14]:
#mean
# t.mean(t1)
# >> RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


# t1.dtype
# >> torch.int64
# Yay! Successfully threw a shape error (organic)


In [18]:
t.mean(t1.type(t.float32)), t1.type(t.float32).mean()

(tensor(5.), tensor(5.))

In [21]:
# sum
t.sum(t2),t2.sum()

(tensor(20), tensor(20))

In [35]:
# t1Mean = t.mean(t1.type(t.float32))
# t.arg

### Argmin
    returns the posn of the element w/smallest val. in a tensor
    
### Argmax
    returns the posn of the element w/largest val. in a tensor

In [41]:
t1.argmin(), t1.argmax(), t2.argmin(), t2.argmax()

(tensor(0), tensor(4), tensor(0), tensor(4))

### Reshaping
reshaping an input tensor to desired shape

### View
...

### Stacking
combining multiple tensors on top of one another, vertical stacking; 
or side by side, horizontal stacking

### Squeezing
removes all `1` dimensions

### Unsqueezing
adding `1` dimensions

### Permute
return a view of the tensor w/dimensions permuted in a certain way


#### Reshaping

In [47]:
t3 = t.arange(1,10)
t3, t3.size()

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [53]:
t4 = t3.reshape([1,9])
t5 = t3.reshape([9,1])
t4, t5

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]))

In [58]:
t6 = t.arange(0,15)
t7 = t6.reshape([3,5])
t8 = t6.reshape([5,3])
t7,t8

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]))

#### Views
    Views carry the mem. of the tensor they're made out of.

In [65]:
t9 = t8.view(5,3)
t9

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [72]:
t8[:1,0]
t8, t9

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]))