In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [4]:
!nvidia-smi

Mon Mar 16 06:08:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [7]:
#CUDA (Compute Unified Device Architecture)

## Intro to Tensors

### Scalar

In [7]:
scalar  = torch.tensor(7)
scalar



tensor(7)

In [15]:
# To get a tensor as a Python int:
scalar.item()

7

In [17]:
scalar.ndim

0

In [18]:
scalar.shape

torch.Size([])

In [20]:
#Vector

vector = torch.tensor([2,1])
vector

tensor([2, 1])

In [22]:
vector.ndim

1

In [23]:
vector.shape

torch.Size([2])

![Scalar](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

## MATRIX

In [31]:
Matrix = torch.tensor([[1,2],[2,3]])

print(Matrix)
print(f"NDIM: {Matrix.ndim}, Shape: {Matrix.shape}")
print(Matrix[0])
print(Matrix[1])

tensor([[1, 2],
        [2, 3]])
NDIM: 2, Shape: torch.Size([2, 2])
tensor([1, 2])
tensor([2, 3])


## TENSOR

In [38]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]]])

print(f"NDIM: {TENSOR.ndim}, Shape: {TENSOR.shape}")

NDIM: 3, Shape: torch.Size([2, 2, 3])


#### MATRICES and TENSORS are always capitalized by convention