## Random TENSORS
    NN use random tensors at first then update iteratively

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [2]:
#Create random TENSOR of size (n, m)

randomTENSOR = torch.rand(3,3,4)
randomTENSOR



tensor([[[0.0827, 0.6618, 0.7522, 0.5867],
         [0.0954, 0.6788, 0.3360, 0.0952],
         [0.3044, 0.1144, 0.6099, 0.4744]],

        [[0.2218, 0.4247, 0.3762, 0.2386],
         [0.2663, 0.8482, 0.0685, 0.8660],
         [0.5926, 0.6512, 0.8042, 0.6367]],

        [[0.3160, 0.3798, 0.2910, 0.2456],
         [0.1997, 0.9970, 0.3043, 0.3721],
         [0.4848, 0.4742, 0.7022, 0.4276]]])

In [3]:
print(f"NDIM: {randomTENSOR.ndim}, Shape: {randomTENSOR.shape}")


NDIM: 3, Shape: torch.Size([3, 3, 4])


In [4]:
#Random TENSOR in the shape of an image TENSOR

randomImgTENSOR = torch.rand(size=(224,224,3))
print(randomImgTENSOR)

tensor([[[0.4485, 0.3482, 0.5697],
         [0.0911, 0.8515, 0.8339],
         [0.6127, 0.0256, 0.6657],
         ...,
         [0.2462, 0.1980, 0.5129],
         [0.5511, 0.4201, 0.7929],
         [0.7011, 0.7053, 0.4169]],

        [[0.3309, 0.0331, 0.4570],
         [0.8112, 0.9003, 0.0608],
         [0.6750, 0.7441, 0.0683],
         ...,
         [0.7351, 0.3184, 0.7362],
         [0.6338, 0.0430, 0.7019],
         [0.1884, 0.5724, 0.6719]],

        [[0.6673, 0.9476, 0.8667],
         [0.3501, 0.3339, 0.4064],
         [0.5507, 0.4539, 0.9663],
         ...,
         [0.6034, 0.2064, 0.9141],
         [0.6300, 0.9639, 0.6087],
         [0.9278, 0.4807, 0.9145]],

        ...,

        [[0.5355, 0.4916, 0.9104],
         [0.6986, 0.0661, 0.1860],
         [0.0562, 0.4594, 0.3998],
         ...,
         [0.2275, 0.2378, 0.2798],
         [0.8621, 0.6810, 0.8296],
         [0.4751, 0.1381, 0.5463]],

        [[0.9337, 0.8875, 0.0078],
         [0.7903, 0.9379, 0.0701],
         [0.

### Zeroes and Ones

In [5]:
# A tensor that only has zeroes (useful for masks)

allZeroes = torch.zeros(3,4)
allZeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# A tensor that only has ones

allOnes = torch.ones(3,4)
allOnes

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
allZeroes * allOnes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
rT1 = torch.rand(3,4)
print(rT1)


rT2 = rT1 - allOnes
rT2

tensor([[0.5459, 0.5738, 0.4774, 0.0145],
        [0.0032, 0.8813, 0.3729, 0.5851],
        [0.1875, 0.0441, 0.3385, 0.8680]])


tensor([[-0.4541, -0.4262, -0.5226, -0.9855],
        [-0.9968, -0.1187, -0.6271, -0.4149],
        [-0.8125, -0.9559, -0.6615, -0.1320]])

#### Creating a range of TENSORS

In [9]:
# rangeTen = torch.arange(start, end, step)
rangeTen = torch.arange(0, 10)
print(rangeTen)

rgT1 = torch.arange(0,11, 2)
print(rgT1)



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10])


#### TENSORS like other TENSORS

In [10]:
# tensors like

tenZeroes = torch.zeros_like(rangeTen)
print(tenZeroes)

tenOnes = torch.ones_like(rangeTen)
print(tenOnes)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [11]:
import random

In [12]:
# rdm = random.randint(0,100000)
rdm = random.random()

likeOtherTensor = torch.full_like(rT1, rdm)
print(likeOtherTensor)

tensor([[0.7913, 0.7913, 0.7913, 0.7913],
        [0.7913, 0.7913, 0.7913, 0.7913],
        [0.7913, 0.7913, 0.7913, 0.7913]])


### Tensor Datatypes

In [13]:
tensorFloat32 = torch.tensor([[3.0],[2.0]])
print(f"Shape: {tensorFloat32.shape}, NDIM: {tensorFloat32.ndim}")
print(tensorFloat32.dtype)

tensorFloat16 = torch.tensor([[3.0],[2.0]], dtype=torch.float16)
print(f"Shape: {tensorFloat16.shape}, NDIM: {tensorFloat16.ndim}")
print(tensorFloat16.dtype)

Shape: torch.Size([2, 1]), NDIM: 2
torch.float32
Shape: torch.Size([2, 1]), NDIM: 2
torch.float16


In [14]:
# Other important parameters

# torch.tensor([], dtype=torch.float32,
#                  device=cuda, #which device the tensor lives on
#                  requires_grad=False) #whether to track gradience for this tensor
# torch.tensor([], dtype=torch.float32, device=GPU, requires_grad=False)
# torch.tensor([], dtype=torch.float32, device=TPU, requires_grad=False)

## TENSOR Attributes

In [15]:
abominationTensor = tensorFloat16*tensorFloat32
print(abominationTensor, abominationTensor.dtype)

tensor([[9.],
        [4.]]) torch.float32


#### Main Takeaway:

    Here it seems that PyTorch tensors are robust enough that even when operating on two tensors of diff. shapes, they yield outputs.

### Other Attributes

In [16]:
print(rT1.shape)
print(rT1.size())
print(rT1.dtype)
print(str(rT1.device).upper())


torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
CPU


## Tensor Operations

In [17]:
rT3 = torch.rand(3,4)
rT4 = torch.rand(3,4)
rT5 = torch.rand(3,3)

print(rT3, "\n", rT4)


tensor([[0.1012, 0.6806, 0.3333, 0.6262],
        [0.4321, 0.7765, 0.2751, 0.1733],
        [0.7320, 0.5321, 0.8256, 0.1450]]) 
 tensor([[0.2608, 0.2282, 0.7383, 0.7846],
        [0.9863, 0.2991, 0.2990, 0.5434],
        [0.4683, 0.9048, 0.9518, 0.6628]])


In [18]:
# Addition

rT3+1
rT4+2

tensor([[2.2608, 2.2282, 2.7383, 2.7846],
        [2.9863, 2.2991, 2.2990, 2.5434],
        [2.4683, 2.9048, 2.9518, 2.6628]])

In [19]:
# Subtrn

rT3 - 3

tensor([[-2.8988, -2.3194, -2.6667, -2.3738],
        [-2.5679, -2.2235, -2.7249, -2.8267],
        [-2.2680, -2.4679, -2.1744, -2.8550]])

In [20]:
# Div
rT3/3

tensor([[0.0337, 0.2269, 0.1111, 0.2087],
        [0.1440, 0.2588, 0.0917, 0.0578],
        [0.2440, 0.1774, 0.2752, 0.0483]])

In [21]:
# # Multiplication of tensors of different shapes
# #Results in an error

# rT6 = rT5*rT3
# print(rT5.shape)

In [22]:
#Multiplying tensors of the same shape

rT7 = rT3*rT4
print(f"{rT7}\nShape: {rT7.shape}")

tensor([[0.0264, 0.1553, 0.2461, 0.4913],
        [0.4262, 0.2323, 0.0823, 0.0942],
        [0.3428, 0.4814, 0.7859, 0.0961]])
Shape: torch.Size([3, 4])


In [23]:
# # Addn & Subrcn of tensors of diff. shapes
# # Results in an error

# # rT8 = rT3+rT5
# # rT9 = rT5+rT3
# print(f"{rT8}\nShape: {rT8.shape}")
# print(f"\n{rT9}\nShape: {rT9.shape}")

#### Pytorch in-built func. 

In [24]:
print(torch.mul(rT3,11))
print(torch.add(rT3, 10))

tensor([[1.1130, 7.4867, 3.6662, 6.8880],
        [4.7536, 8.5411, 3.0259, 1.9061],
        [8.0520, 5.8530, 9.0818, 1.5945]])
tensor([[10.1012, 10.6806, 10.3333, 10.6262],
        [10.4321, 10.7765, 10.2751, 10.1733],
        [10.7320, 10.5321, 10.8256, 10.1450]])


In [25]:
print(torch.sub(rT3, 100))
print(torch.subtract(rT3, 100))

# def isSim(m,n):
#     if torch.equal(m,n):
#         return True
#     # else:
#     #     return False
#     return False

rt10 = torch.subtract(rT3, 1000)
rt11 = torch.sub(rT3, 1000)

# isSim(rt10, rt11)
print(torch.equal(rt10, rt11))
print(torch.equal(rt10, rT3))

tensor([[-99.8988, -99.3194, -99.6667, -99.3738],
        [-99.5679, -99.2235, -99.7249, -99.8267],
        [-99.2680, -99.4679, -99.1744, -99.8550]])
tensor([[-99.8988, -99.3194, -99.6667, -99.3738],
        [-99.5679, -99.2235, -99.7249, -99.8267],
        [-99.2680, -99.4679, -99.1744, -99.8550]])
True
False


In [26]:
print(torch.div(rT3, 3))
print(torch.divide(rT3, 3))

tensor([[0.0337, 0.2269, 0.1111, 0.2087],
        [0.1440, 0.2588, 0.0917, 0.0578],
        [0.2440, 0.1774, 0.2752, 0.0483]])
tensor([[0.0337, 0.2269, 0.1111, 0.2087],
        [0.1440, 0.2588, 0.0917, 0.0578],
        [0.2440, 0.1774, 0.2752, 0.0483]])


### Matrix Multplcn / Dot Product

![](https://miro.medium.com/v2/1*YGcMQSr0ge_DGn96WnEkZw.png)

In [27]:
%%time
%time
print(torch.matmul(torch.tensor([1,2,3]), torch.tensor([1,2,3])))
# Matrix mult: 1*1+2*2+3*3
print(1*1+2*2+3*3)

# a.b

torch.matmul(torch.rand(3,2), torch.rand(2,3))

a,b = torch.rand(3,2),torch.rand(2,3)

torch.matmul(a,b)
# torch.matmul(torch.rand(3,1,2), torch.rand(2,3,1)) #wrong

# torch.dot(a,b) #wrong, expects 1D tensors



CPU times: total: 0 ns
Wall time: 3.1 μs
tensor(14)
14
CPU times: total: 0 ns
Wall time: 5.98 ms


tensor([[0.1107, 0.6903, 0.5228],
        [0.1696, 1.2130, 0.9836],
        [0.1245, 0.8189, 0.6382]])

### Rules for Matrix Multiplication

#### 1.) Inner dimensions must match
    
    Tensors w/ shape (m,n) and (n,m) can bet matmulled (matrix multiplied).
    Ex.: (2,3).(3,2)

In [28]:
rt12 = torch.rand(2,3)
rt13 = torch.rand(3,2)
rt14 = torch.rand(2,3)

print(torch.matmul(rt12,rt13))
# print(torch.matmul(rt12,rt14)) #Throws error


tensor([[0.8911, 0.5000],
        [0.5061, 0.2747]])


#### 2.) Resulting tensor of (m,n).(n,m) is ALWAYS of size (m,m) (outer dimensions)

In [29]:
print(rt12.shape, rt13.shape)
print(torch.matmul(rt12,rt13).shape)

torch.Size([2, 3]) torch.Size([3, 2])
torch.Size([2, 2])


For easy understanding and visualization
[this website](matrixmultiplication.xyz) is very helpful

#### Shape Errors w/MM

In [33]:
tA = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

tB = torch.tensor([[11,12,13],
                   [14,15,16],
                   [17,18,19]])

print(f"""Tensor A shape: {tA.shape}
Tensor B shape: {tB.shape}""")

Tensor A shape: torch.Size([3, 3])
Tensor B shape: torch.Size([3, 3])


In [37]:
torch.mm(tA,tB)
# torch.matmul(tA,tB)

tensor([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])

In [44]:
tC = torch.tensor([[1,2,3],
                   [4,5,6]])

tD = torch.tensor([[7,8,9],
                   [11,12,13]])

tC.shape, tD.shape
# cannot be matmulled

(torch.Size([2, 3]), torch.Size([2, 3]))

#### Transpose
    Flipping a tensor by 90 degrees.
    Replacing the dimensions

In [ ]:
#Transposing tD
print(torch.tensor(tD.T))

print(torch.mm(tC,tD.T))
#Success!