## Random TENSORS
    NN use random tensors at first then update iteratively

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [2]:
#Create random TENSOR of size (n, m)

randomTENSOR = torch.rand(3,3,4)
randomTENSOR



tensor([[[0.2547, 0.5783, 0.8802, 0.7330],
         [0.9162, 0.7247, 0.3164, 0.5938],
         [0.1215, 0.0174, 0.4004, 0.6877]],

        [[0.1361, 0.4365, 0.4329, 0.7105],
         [0.8928, 0.9582, 0.0545, 0.5336],
         [0.8457, 0.4809, 0.5044, 0.5607]],

        [[0.8299, 0.6708, 0.9520, 0.1606],
         [0.7265, 0.3047, 0.4118, 0.1012],
         [0.8002, 0.9945, 0.9535, 0.5820]]])

In [3]:
print(f"NDIM: {randomTENSOR.ndim}, Shape: {randomTENSOR.shape}")


NDIM: 3, Shape: torch.Size([3, 3, 4])


In [4]:
#Random TENSOR in the shape of an image TENSOR

randomImgTENSOR = torch.rand(size=(224,224,3))
print(randomImgTENSOR)

tensor([[[0.8042, 0.7680, 0.7626],
         [0.6114, 0.1621, 0.6845],
         [0.3291, 0.1872, 0.5057],
         ...,
         [0.4202, 0.2833, 0.1718],
         [0.5679, 0.1687, 0.5328],
         [0.0445, 0.5555, 0.9215]],

        [[0.9748, 0.2751, 0.9656],
         [0.7829, 0.2322, 0.3150],
         [0.8517, 0.6923, 0.2114],
         ...,
         [0.8503, 0.1770, 0.1027],
         [0.1335, 0.9888, 0.3278],
         [0.6071, 0.2524, 0.9810]],

        [[0.4863, 0.4804, 0.1929],
         [0.7633, 0.6250, 0.2891],
         [0.5510, 0.5871, 0.0091],
         ...,
         [0.5375, 0.5545, 0.7687],
         [0.4917, 0.2419, 0.9098],
         [0.3111, 0.8197, 0.1538]],

        ...,

        [[0.1531, 0.9629, 0.4686],
         [0.8217, 0.8222, 0.7881],
         [0.3800, 0.3939, 0.9443],
         ...,
         [0.9112, 0.5406, 0.9701],
         [0.5357, 0.1176, 0.5469],
         [0.4071, 0.3060, 0.5435]],

        [[0.6085, 0.4337, 0.1397],
         [0.0117, 0.3635, 0.2054],
         [0.

### Zeroes and Ones

In [5]:
# A tensor that only has zeroes (useful for masks)

allZeroes = torch.zeros(3,4)
allZeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# A tensor that only has ones

allOnes = torch.ones(3,4)
allOnes

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
allZeroes * allOnes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
rT1 = torch.rand(3,4)
print(rT1)


rT2 = rT1 - allOnes
rT2

tensor([[0.4098, 0.1607, 0.8128, 0.9424],
        [0.1263, 0.3727, 0.4365, 0.1436],
        [0.9531, 0.2471, 0.4792, 0.5784]])


tensor([[-0.5902, -0.8393, -0.1872, -0.0576],
        [-0.8737, -0.6273, -0.5635, -0.8564],
        [-0.0469, -0.7529, -0.5208, -0.4216]])

#### Creating a range of TENSORS

In [ ]:
# rangeTen = torch.arange(start, end, step)
rangeTen = torch.arange(0, 10)
print(rangeTen)

rgT1 = torch.arange(0,11, 2)
print(rgT1)



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([ 0,  2,  4,  6,  8, 10])

#### TENSORS like other TENSORS

In [25]:
# tensors like

tenZeroes = torch.zeros_like(rangeTen)
print(tenZeroes)

tenOnes = torch.ones_like(rangeTen)
print(tenOnes)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [27]:
import random

In [47]:
# rdm = random.randint(0,100000)
rdm = random.random()

likeOtherTensor = torch.full_like(rT1, rdm)
print(likeOtherTensor)

tensor([[0.2035, 0.2035, 0.2035, 0.2035],
        [0.2035, 0.2035, 0.2035, 0.2035],
        [0.2035, 0.2035, 0.2035, 0.2035]])


### Tensor Datatypes

In [59]:
tensorFloat32 = torch.tensor([[3.0],[2.0]])
print(f"Shape: {tensorFloat32.shape}, NDIM: {tensorFloat32.ndim}")
print(tensorFloat32.dtype)

tensorFloat16 = torch.tensor([[3.0],[2.0]], dtype=torch.float16)
print(f"Shape: {tensorFloat16.shape}, NDIM: {tensorFloat16.ndim}")
print(tensorFloat16.dtype)

Shape: torch.Size([2, 1]), NDIM: 2
torch.float32
Shape: torch.Size([2, 1]), NDIM: 2
torch.float16


In [62]:
# Other important parameters

# torch.tensor([], dtype=torch.float32,
#                  device=cuda, #which device the tensor lives on
#                  requires_grad=False) #whether to track gradience for this tensor
# torch.tensor([], dtype=torch.float32, device=GPU, requires_grad=False)
# torch.tensor([], dtype=torch.float32, device=TPU, requires_grad=False)

## TENSOR Attributes

In [ ]:
abominationTensor = tensorFloat16*tensorFloat32
print(abominationTensor, abominationTensor.dtype)

tensor([[9.],
        [4.]]) torch.float32
