## Random TENSORS
    NN use random tensors at first then update iteratively

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [9]:
#Create random TENSOR of size (n, m)

randomTENSOR = torch.rand(3,3,4)
randomTENSOR



tensor([[[0.2858, 0.9170, 0.9641, 0.1530],
         [0.0377, 0.9051, 0.8448, 0.4798],
         [0.5082, 0.7334, 0.4317, 0.6401]],

        [[0.6462, 0.5595, 0.5807, 0.3878],
         [0.8986, 0.7459, 0.0338, 0.8545],
         [0.7704, 0.0687, 0.2138, 0.8757]],

        [[0.8986, 0.6534, 0.0011, 0.5600],
         [0.5769, 0.4840, 0.9693, 0.0347],
         [0.1173, 0.1349, 0.8963, 0.0866]]])

In [11]:
print(f"NDIM: {randomTENSOR.ndim}, Shape: {randomTENSOR.shape}")


NDIM: 3, Shape: torch.Size([3, 3, 4])


In [15]:
#Random TENSOR in the shape of an image TENSOR

randomImgTENSOR = torch.rand(size=(224,224,3))
print(randomImgTENSOR)

tensor([[[0.6225, 0.8557, 0.0693],
         [0.7846, 0.4538, 0.5148],
         [0.5721, 0.5261, 0.7214],
         ...,
         [0.7026, 0.6643, 0.8487],
         [0.2523, 0.1506, 0.7539],
         [0.8271, 0.3528, 0.0300]],

        [[0.2107, 0.0847, 0.5214],
         [0.0577, 0.4302, 0.8825],
         [0.0062, 0.2982, 0.8786],
         ...,
         [0.3612, 0.9234, 0.4348],
         [0.5107, 0.3611, 0.2284],
         [0.7946, 0.9069, 0.4212]],

        [[0.3557, 0.0175, 0.5687],
         [0.6927, 0.0705, 0.4147],
         [0.8195, 0.3558, 0.8558],
         ...,
         [0.0427, 0.5084, 0.2077],
         [0.8406, 0.6657, 0.4176],
         [0.7678, 0.4630, 0.2737]],

        ...,

        [[0.4901, 0.9909, 0.7435],
         [0.4803, 0.4421, 0.3683],
         [0.4228, 0.2545, 0.8004],
         ...,
         [0.1054, 0.9657, 0.0431],
         [0.6812, 0.8758, 0.7893],
         [0.8878, 0.7127, 0.4009]],

        [[0.5034, 0.9774, 0.0738],
         [0.3063, 0.9964, 0.5849],
         [0.

### Zeroes and Ones

In [19]:
# A tensor that only has zeroes (useful for masks)

allZeroes = torch.zeros(3,4)
allZeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# A tensor that only has ones

allOnes = torch.ones(3,4)
allOnes

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
allZeroes * allOnes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])