## Random TENSORS
    NN use random tensors at first then update iteratively

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [2]:
#Create random TENSOR of size (n, m)

randomTENSOR = torch.rand(3,3,4)
randomTENSOR



tensor([[[0.2547, 0.5783, 0.8802, 0.7330],
         [0.9162, 0.7247, 0.3164, 0.5938],
         [0.1215, 0.0174, 0.4004, 0.6877]],

        [[0.1361, 0.4365, 0.4329, 0.7105],
         [0.8928, 0.9582, 0.0545, 0.5336],
         [0.8457, 0.4809, 0.5044, 0.5607]],

        [[0.8299, 0.6708, 0.9520, 0.1606],
         [0.7265, 0.3047, 0.4118, 0.1012],
         [0.8002, 0.9945, 0.9535, 0.5820]]])

In [3]:
print(f"NDIM: {randomTENSOR.ndim}, Shape: {randomTENSOR.shape}")


NDIM: 3, Shape: torch.Size([3, 3, 4])


In [4]:
#Random TENSOR in the shape of an image TENSOR

randomImgTENSOR = torch.rand(size=(224,224,3))
print(randomImgTENSOR)

tensor([[[0.8042, 0.7680, 0.7626],
         [0.6114, 0.1621, 0.6845],
         [0.3291, 0.1872, 0.5057],
         ...,
         [0.4202, 0.2833, 0.1718],
         [0.5679, 0.1687, 0.5328],
         [0.0445, 0.5555, 0.9215]],

        [[0.9748, 0.2751, 0.9656],
         [0.7829, 0.2322, 0.3150],
         [0.8517, 0.6923, 0.2114],
         ...,
         [0.8503, 0.1770, 0.1027],
         [0.1335, 0.9888, 0.3278],
         [0.6071, 0.2524, 0.9810]],

        [[0.4863, 0.4804, 0.1929],
         [0.7633, 0.6250, 0.2891],
         [0.5510, 0.5871, 0.0091],
         ...,
         [0.5375, 0.5545, 0.7687],
         [0.4917, 0.2419, 0.9098],
         [0.3111, 0.8197, 0.1538]],

        ...,

        [[0.1531, 0.9629, 0.4686],
         [0.8217, 0.8222, 0.7881],
         [0.3800, 0.3939, 0.9443],
         ...,
         [0.9112, 0.5406, 0.9701],
         [0.5357, 0.1176, 0.5469],
         [0.4071, 0.3060, 0.5435]],

        [[0.6085, 0.4337, 0.1397],
         [0.0117, 0.3635, 0.2054],
         [0.

### Zeroes and Ones

In [5]:
# A tensor that only has zeroes (useful for masks)

allZeroes = torch.zeros(3,4)
allZeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# A tensor that only has ones

allOnes = torch.ones(3,4)
allOnes

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
allZeroes * allOnes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
rT1 = torch.rand(3,4)
print(rT1)


rT2 = rT1 - allOnes
rT2

tensor([[0.4098, 0.1607, 0.8128, 0.9424],
        [0.1263, 0.3727, 0.4365, 0.1436],
        [0.9531, 0.2471, 0.4792, 0.5784]])


tensor([[-0.5902, -0.8393, -0.1872, -0.0576],
        [-0.8737, -0.6273, -0.5635, -0.8564],
        [-0.0469, -0.7529, -0.5208, -0.4216]])

#### Creating a range of TENSORS

In [ ]:
# rangeTen = torch.arange(start, end, step)
rangeTen = torch.arange(0, 10)
print(rangeTen)

rgT1 = torch.arange(0,11, 2)
print(rgT1)



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([ 0,  2,  4,  6,  8, 10])

#### TENSORS like other TENSORS

In [25]:
# tensors like

tenZeroes = torch.zeros_like(rangeTen)
print(tenZeroes)

tenOnes = torch.ones_like(rangeTen)
print(tenOnes)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [3]:
import random

In [47]:
# rdm = random.randint(0,100000)
rdm = random.random()

likeOtherTensor = torch.full_like(rT1, rdm)
print(likeOtherTensor)

tensor([[0.2035, 0.2035, 0.2035, 0.2035],
        [0.2035, 0.2035, 0.2035, 0.2035],
        [0.2035, 0.2035, 0.2035, 0.2035]])


### Tensor Datatypes

In [59]:
tensorFloat32 = torch.tensor([[3.0],[2.0]])
print(f"Shape: {tensorFloat32.shape}, NDIM: {tensorFloat32.ndim}")
print(tensorFloat32.dtype)

tensorFloat16 = torch.tensor([[3.0],[2.0]], dtype=torch.float16)
print(f"Shape: {tensorFloat16.shape}, NDIM: {tensorFloat16.ndim}")
print(tensorFloat16.dtype)

Shape: torch.Size([2, 1]), NDIM: 2
torch.float32
Shape: torch.Size([2, 1]), NDIM: 2
torch.float16


In [62]:
# Other important parameters

# torch.tensor([], dtype=torch.float32,
#                  device=cuda, #which device the tensor lives on
#                  requires_grad=False) #whether to track gradience for this tensor
# torch.tensor([], dtype=torch.float32, device=GPU, requires_grad=False)
# torch.tensor([], dtype=torch.float32, device=TPU, requires_grad=False)

## TENSOR Attributes

In [65]:
abominationTensor = tensorFloat16*tensorFloat32
print(abominationTensor, abominationTensor.dtype)

tensor([[9.],
        [4.]]) torch.float32


#### Main Takeaway:

    Here it seems that PyTorch tensors are robust enough that even when operating on two tensors of diff. shapes, they yield outputs.

### Other Attributes

In [84]:
print(rT1.shape)
print(rT1.size())
print(rT1.dtype)
print(str(rT1.device).upper())


torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
CPU


## Tensor Operations

In [5]:
rT3 = torch.rand(3,4)
rT4 = torch.rand(3,4)
rT5 = torch.rand(3,3)

print(rT3, "\n", rT4)


tensor([[0.5210, 0.6486, 0.3201, 0.8167],
        [0.6605, 0.2324, 0.4388, 0.7322],
        [0.9116, 0.2138, 0.6024, 0.9670]]) 
 tensor([[0.6986, 0.3671, 0.8108, 0.0882],
        [0.7094, 0.2499, 0.8376, 0.9382],
        [0.9638, 0.6786, 0.7659, 0.7481]])


In [8]:
# Addition

rT3+1
rT4+2

tensor([[2.6986, 2.3671, 2.8108, 2.0882],
        [2.7094, 2.2499, 2.8376, 2.9382],
        [2.9638, 2.6786, 2.7659, 2.7481]])

In [10]:
# Subtrn

rT3 - 3

tensor([[-2.4790, -2.3514, -2.6799, -2.1833],
        [-2.3395, -2.7676, -2.5612, -2.2678],
        [-2.0884, -2.7862, -2.3976, -2.0330]])

In [ ]:
# Div
rT3/3

tensor([[0.1737, 0.2162, 0.1067, 0.2722],
        [0.2202, 0.0775, 0.1463, 0.2441],
        [0.3039, 0.0713, 0.2008, 0.3223]])

In [109]:
# # Multiplication of tensors of different shapes
# #Results in an error

# rT6 = rT5*rT3
# print(rT5.shape)

In [98]:
#Multiplying tensors of the same shape

rT7 = rT3*rT4
print(f"{rT7}\nShape: {rT7.shape}")

tensor([[0.0734, 0.3104, 0.1882, 0.2808],
        [0.0075, 0.3738, 0.1212, 0.3259],
        [0.6966, 0.0436, 0.4006, 0.2165]])
Shape: torch.Size([3, 4])


In [108]:
# # Addn & Subrcn of tensors of diff. shapes
# # Results in an error

# # rT8 = rT3+rT5
# # rT9 = rT5+rT3
# print(f"{rT8}\nShape: {rT8.shape}")
# print(f"\n{rT9}\nShape: {rT9.shape}")

#### Pytorch in-built func. 

In [33]:
print(torch.mul(rT3,11))
print(torch.add(rT3, 10))

tensor([[ 5.7309,  7.1345,  3.5209,  8.9837],
        [ 7.2659,  2.5560,  4.8267,  8.0541],
        [10.0277,  2.3517,  6.6268, 10.6368]])
tensor([[10.5210, 10.6486, 10.3201, 10.8167],
        [10.6605, 10.2324, 10.4388, 10.7322],
        [10.9116, 10.2138, 10.6024, 10.9670]])


In [35]:
print(torch.sub(rT3, 100))
print(torch.subtract(rT3, 100))

# def isSim(m,n):
#     if torch.equal(m,n):
#         return True
#     # else:
#     #     return False
#     return False

rt10 = torch.subtract(rT3, 1000)
rt11 = torch.sub(rT3, 1000)

# isSim(rt10, rt11)
print(torch.equal(rt10, rt11))
print(torch.equal(rt10, rT3))

tensor([[-99.4790, -99.3514, -99.6799, -99.1833],
        [-99.3395, -99.7676, -99.5612, -99.2678],
        [-99.0884, -99.7862, -99.3976, -99.0330]])
tensor([[-99.4790, -99.3514, -99.6799, -99.1833],
        [-99.3395, -99.7676, -99.5612, -99.2678],
        [-99.0884, -99.7862, -99.3976, -99.0330]])
True
False


In [38]:
print(torch.div(rT3, 3))
print(torch.divide(rT3, 3))

tensor([[0.1737, 0.2162, 0.1067, 0.2722],
        [0.2202, 0.0775, 0.1463, 0.2441],
        [0.3039, 0.0713, 0.2008, 0.3223]])
tensor([[0.1737, 0.2162, 0.1067, 0.2722],
        [0.2202, 0.0775, 0.1463, 0.2441],
        [0.3039, 0.0713, 0.2008, 0.3223]])


### Matrix Multplcn / Dot Product

![](https://miro.medium.com/v2/1*YGcMQSr0ge_DGn96WnEkZw.png)

In [13]:
%%time
%time
print(torch.matmul(torch.tensor([1,2,3]), torch.tensor([1,2,3])))
# Matrix mult: 1*1+2*2+3*3
print(1*1+2*2+3*3)

# a.b

torch.matmul(torch.rand(3,2), torch.rand(2,3))

a,b = torch.rand(3,2),torch.rand(2,3)

torch.matmul(a,b)
# torch.matmul(torch.rand(3,1,2), torch.rand(2,3,1)) #wrong

# torch.dot(a,b) #wrong, expects 1D tensors



CPU times: total: 0 ns
Wall time: 5.96 μs
tensor(14)
14
CPU times: total: 0 ns
Wall time: 1.74 ms


tensor([[0.5731, 0.5007, 0.5772],
        [0.4812, 0.3000, 0.3451],
        [0.7436, 0.7386, 0.8518]])

### Rules for MM

#### 1.) Inner dimensions must match
    
    Tensors w/ shape (m,n) and (n,m) can bet matmulled (matrix multiplied).
    Ex.: (2,3).(3,2)

In [18]:
rt12 = torch.rand(2,3)
rt13 = torch.rand(3,2)
rt14 = torch.rand(2,3)

print(torch.matmul(rt12,rt13))
# print(torch.matmul(rt12,rt14)) #Throws error


tensor([[1.1090, 0.8056],
        [0.7540, 0.5264]])


#### 2.) Resulting tensor of (m,n).(n,m) is ALWAYS of size (m,m) (outer dimensions)

In [20]:
print(rt12.shape, rt13.shape)
print(torch.matmul(rt12,rt13).shape)

torch.Size([2, 3]) torch.Size([3, 2])
torch.Size([2, 2])
